# Generated by Django 3.0.1 on 2019-12-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191227_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='condition_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
