# Generated by Django 3.0.1 on 2019-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_order_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='descriptionorder',
            name='title',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
