# Generated by Django 3.0.1 on 2019-12-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191227_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.Executer'),
        ),
        migrations.CreateModel(
            name='ResponseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('condition', models.BooleanField(default=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_orders', to='profiles.Executer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_orders', to='profiles.Order')),
            ],
        ),
        migrations.AddField(
            model_name='executer',
            name='orders_response',
            field=models.ManyToManyField(related_name='executers', to='profiles.ResponseOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='response_orders',
            field=models.ManyToManyField(related_name='orders', to='profiles.ResponseOrder'),
        ),
    ]
