# Generated by Django 3.0.1 on 2019-12-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191228_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responseorder',
            old_name='executor',
            new_name='executer',
        ),
    ]
