# Generated by Django 3.0.1 on 2019-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20191228_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseorder',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
