# Generated by Django 3.0.1 on 2019-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20191228_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='response_orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='profiles.ResponseOrder'),
        ),
    ]
